### ISSUE TITLE
VCPKG Port

### ISSUE THREAD

**Issue by ankurvdev** [saucer/saucer#3]
Love the project. 
I've been looking for something like this for a while. 

Would you guys be willing to create a vcpkg-port for this so its easier to incorporate into external projects ?

I have a cross-platform (linux,win32,uwp,android) app where I'm currently embedding a (localhost) web-server just to get c++/javascript interop and i'd love to port it to the native-interop this uses.
Using VCPKG really simplifies the cross-platform workflow

I believe what's needed here (CMakeLists.txt) is to use find_package (first) to detect the external dependencies before resorting to FetchContent.

**Comment by Curve** [comment]
I can look into this soon ^^

**Comment by Curve** [comment]
Actually I'm not entirely sure if publishing this on vcpkg will work because on Windows we depend on Webview2 which as far as I'm aware hasn't been published to vcpkg yet¹.

Currently the CMakeLists downloads the NuGet executable to download WebView2, I'm not sure if this is compliant with the packaging rules.

¹ https://github.com/MicrosoftEdge/WebView2Feedback/issues/889

**Comment by ankurvdev** [comment]
There's already a few examples of ports that download dependency nuget packages in vcpkg 

https://github.com/microsoft/vcpkg/blob/89c4fdfbe4a0a4c386513f35a573e1df69150441/ports/azure-kinect-sensor-sdk/portfile.cmake#L60

So the portfile.cmake can pre-download the WebView2 nuget and which can be used during the build/install process.

**Comment by Curve** [comment]
Alright, I'll look into making a portfile, however I'll first finish some of the remaining things on my TODO-List before actually publishing the project to the vcpkg repo because I want to make a release first ^^

**Comment by Curve** [comment]
Alright, I'll probably delay the support for language bindings and then release 0.1  pretty soon, with that I'll open a PR for saucer at vcpkg

**Comment by Curve** [comment]
@ankurvdev I've put up a PR for this: https://github.com/microsoft/vcpkg/pull/25111

**Comment by Curve** [comment]
This is proving more difficult than expected, the build fails on Linux because vcpkg doesn't support qt5-webengine statically, and because of that the whole build fails for Linux. I'm not sure how this should be handled.

**Comment by Curve** [comment]
> 

Saucer already supports Qt6 but as far as I'm aware it's vcpkg port suffers from the same problems

**Comment by Curve** [comment]
I'll wait for further replies on my PR and close this issue as soon as the PR gets merged.

Once it's merged I'll look into making a port-overlay ^^

Due to vcpkg not being as cross-platform friendly as I anticipated I'd suggest to prefer tools like CPM or maybe Conan.  
However I'm not sure if Conan suffers from the same problems - I may look into making a conan package soon.

**Comment by Curve** [comment]
The port has been merged :partying_face:

**Comment by Curve** [comment]
Btw, the Linux issues have been resolved as of lately, you can now install saucer from vcpkg with virtually no extra extra steps

**Comment by ankurvdev** [comment]
Thanks a lot for the great work. 
I'm eager to try it out as soon as I can find the time.

**Comment by Curve** [comment]
> Thanks a lot for the great work. 
> I'm eager to try it out as soon as I can find the time. 

Always a pleasure!
The vcpkg installation instructions are on the website ^^
